#
# Copyright (C) 2024 Confluent, Inc.
#

name: parallel-consumer
lang: java
lang_version: 17
github:
    enable: true
    repo_name: confluentinc/parallel-consumer
git:
    enable: true
semaphore:
    enable: true
    pipeline_enable: false
sonarqube:
  enable: false
tasks:
  - name: release
    scheduled: False
    branch: "master"
    pipeline_file: .semaphore/release.yml
    parameters:
      - name: PROJECT_VERSION
        required: True
        default_value: "X.Y.Z"
      - name: NEXT_PROJECT_VERSION
        required: True
        default_value: "X.Y.Z-SNAPSHOT"