#
# Copyright (C) 2024 Confluent, Inc.
#

name: parallel-consumer
lang: java
lang_version: 17
github:
    enable: true
    repo_name: confluentinc/parallel-consumer
git:
    enable: true
semaphore:
    enable: true
    pipeline_enable: false
make:
  enable: true
  update_makefile: false
  enable_updates: true
sonarqube:
  enable: false