#
# Copyright (C) 2024 Confluent, Inc.
#

name: parallel-consumer
lang: java
lang_version: '17'
git:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  tasks:
    - name: release
      branch: master
      pipeline_file: .semaphore/release.yml
      parameters:
        - name: PROJECT_VERSION
          required: true
          default_value: X.Y.Z
        - name: NEXT_PROJECT_VERSION
          required: true
          default_value: X.Y.Z-SNAPSHOT
sonarqube:
  enable: false
