{
 "title": "Parallel Consumer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{__name__}}-{{id}}"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\",id=\"G1 Old Gen\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Parallel consumer current state",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pc_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Worker Completed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(executor_completed_tasks_total[1m])\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Worker Queued Tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "rate(executor_queued_tasks[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Work Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Partitions",
   "type": "stat",
   "description": "Number of partitions processed by the parallel-consumer",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pc_partitions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shards",
   "type": "stat",
   "description": "Number of processing shards ",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pc_shards", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Paused Partitions",
   "type": "stat",
   "description": "Number of paused partitions",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pc_paused_partitions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Inflight",
   "type": "stat",
   "description": "Number of inflight records processing",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pc_records_inflight", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Waiting Selection",
   "type": "stat",
   "description": "Number of queued records awaiting selection ",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pc_records_waiting", "legendFormat": "__auto" }
   ]
  },
  { "title": "Shard Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Processed Records Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "irate(pc_successfully_processed_records_total[1m])",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Failed Records Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 25 },
   "targets": [
    {
     "expr": "irate(pc_failed_processed_records_total[1m])",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Error Rate ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pc_failed_processed_records_total[1m]))/(sum(rate(pc_failed_processed_records_total[1m]))+sum(rate(pc_successfully_processed_records_total[1m])))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shard Size ",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pc_shard_size", "legendFormat": "{{shard}}" }
   ]
  },
  {
   "title": "User Function Processing Time ",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 31 },
   "targets": [
    {
     "expr": "pc_user_function_processing_time_seconds",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Partition State  Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Partition Offsets Summary",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " pc_incomplete_offsets_partition\n ",
     "legendFormat": "{{__name__}}-{{topic}}-{{partition}}"
    },
    {
     "expr": "pc_highest_complete_offset_partition",
     "legendFormat": "{{__name__}}-{{topic}}-{{partition}}"
    },
    {
     "expr": "pc_highest_sequential_succeeded_offset_partition",
     "legendFormat": "{{__name__}}-{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Partition Offsets Summary",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " pc_incomplete_offsets_partition\n ",
     "legendFormat": "{{__name__}}-{{topic}}-{{partition}}"
    },
    {
     "expr": "pc_highest_complete_offset_partition",
     "legendFormat": "{{__name__}}-{{topic}}-{{partition}}"
    },
    {
     "expr": "pc_highest_sequential_succeeded_offset_partition",
     "legendFormat": "{{__name__}}-{{topic}}-{{partition}}"
    }
   ]
  },
  { "title": "Encoding Compression Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Most Frequent Encoding",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "targets": [
    { "expr": "pc_encoding_usage_total", "legendFormat": "{{codec}}" }
   ]
  },
  {
   "title": "Encoding Time ",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "targets": [
    { "expr": "pc_avg_encoding_time_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Encoding Time ",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pc_avg_encoding_time_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Encoding Metadata Payload vs Offsets Ratio",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pc_payload_ratio_used", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Encoding Metadata Payload vs Used Space Ratio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pc_metadata_space_used", "legendFormat": "{{quantile}}" }
   ]
  },
  { "title": "Kafka Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_max",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_bytes_consumed_rate",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}