#
# Copyright (C) 2020-2022 Confluent, Inc.
#

version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${CP_VERSION:-7.3.0}
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: "echo stat | nc localhost $$ZOOKEEPER_CLIENT_PORT"

  kafka:
    image: confluentinc/cp-server:${CP_VERSION:-7.3.0}
    container_name: kafka-broker
    restart: unless-stopped
    healthcheck:
      interval: 10s
      retries: 20
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"

  prometheus:
    image: prom/prometheus:v2.40.5
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.2.4
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

  parallel-consumer:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -Dlog4j.logLevel=DEBUG -Xmx12g
      JAVA_TOOL_OPTIONS: -Dlog4j.logLevel=DEBUG -Xmx8g
    ports:
      - 7001:7001

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:
